In [1]:
import cv2
from keras.models import load_model
from PIL import Image
import numpy as np

c:\Users\ADMIN\miniconda3\envs\brain_tumor_detection\Lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.2, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "


In [2]:
model=load_model('Braintumor10EpochsCategorical.h5')

In [3]:
image=cv2.imread('no2.jpg')
img=Image.fromarray(image)    #converts the image to PIL format
img=img.resize((64, 64))
img=np.array(img)           #converts the image to numpy array
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [4]:
input_img = np.expand_dims(img, axis=0) #Expand dims so the input is (num images, x, y, channels)
result = model.predict(input_img) #Predict the image
predicted_class = np.argmax(result, axis=1)   #Get the class with highest probability
print(predicted_class)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step
[0]
