In [49]:
import cv2
from keras.models import load_model
from PIL import Image
import numpy as np

In [50]:
model=load_model('Braintumor10EpochsCategorical.h5')

In [51]:
image=cv2.imread('no2.jpg')
img=Image.fromarray(image)    #converts the image to PIL format
img=img.resize((64, 64))
img=np.array(img)           #converts the image to numpy array
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [52]:
input_img = np.expand_dims(img, axis=0) #Expand dims so the input is (num images, x, y, channels)
result = model.predict(input_img) #Predict the image
predicted_class = np.argmax(result, axis=1)   #Get the class with highest probability
print(predicted_class)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
[0]
